environment: production

image:
  repository: aravindacr.azurecr.io/fitbuddy-frontend
  tag: latest

service:
  port: 80

workloadIdentity:
  enabled: true
  clientId: "YOUR-AZURE-MANAGED-IDENTITY-CLIENT-ID"

replicaCount: 3

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
