environment: dev
image:
  repository: acrfitbuddyprod.azurecr.io/frontend
  tag: 9b2c6f4
service:
  port: 80
replicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
resources:
  requests:
    cpu: "25m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"
workloadIdentity:
  enabled: true
  clientId: "YOUR-AZURE-MANAGED-IDENTITY-CLIENT-ID"
