apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fitbuddy-akv-spc-{{ .Chart.Name }}
spec:
  provider: azure
  secretObjects:
  - secretName: bodygpt-secrets
    type: Opaque
    data:
    - objectName: MONGO-URI
      key: MONGO_URI
    - objectName: JWT-ACCESS-SECRET
      key: JWT_ACCESS_SECRET
    - objectName: JWT-REFRESH-SECRET
      key: JWT_REFRESH_SECRET
    - objectName: AZURE-OPENAI-API-KEY
      key: AZURE_OPENAI_API_KEY
    - objectName: AZURE-AI-FOUNDRY-ENDPOINT
      key: AZURE_AI_FOUNDRY_ENDPOINT
    - objectName: AZURE-SERVICEBUS-CONNECTION-STRING
      key: AZURE_SERVICEBUS_CONNECTION_STRING
    - objectName: AZURE-STORAGE-CONNECTION-STRING
      key: AZURE_STORAGE_CONNECTION_STRING
    - objectName: SMTP-USER
      key: SMTP_USER
    - objectName: SMTP-PASS
      key: SMTP_PASS
    - objectName: AZURE-AI-SEARCH-ENDPOINT
      key: AZURE_AI_SEARCH_ENDPOINT
    - objectName: AZURE-AI-SEARCH-KEY
      key: AZURE_AI_SEARCH_KEY
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.workloadIdentity.clientId | quote }}
    tenantId: {{ .Values.workloadIdentity.tenantId | quote }}
    keyvaultName: {{ .Values.keyVaultName | quote }}
    objects: |
      array:
        - |
          objectName: MONGO-URI
          objectType: secret
        - |
          objectName: JWT-ACCESS-SECRET
          objectType: secret
        - |
          objectName: JWT-REFRESH-SECRET
          objectType: secret
        - |
          objectName: AZURE-OPENAI-API-KEY
          objectType: secret
        - |
          objectName: AZURE-AI-FOUNDRY-ENDPOINT
          objectType: secret
        - |
          objectName: AZURE-SERVICEBUS-CONNECTION-STRING
          objectType: secret
        - |
          objectName: AZURE-STORAGE-CONNECTION-STRING
          objectType: secret
        - |
          objectName: SMTP-USER
          objectType: secret
        - |
          objectName: SMTP-PASS
          objectType: secret
        - |
          objectName: AZURE-AI-SEARCH-ENDPOINT
          objectType: secret
        - |
          objectName: AZURE-AI-SEARCH-KEY
          objectType: secret
