applications:
  - name: fitbuddy-dev
    namespace: dev
    valueFile: values-dev.yaml
    repoURL: https://github.com/FitBuddy-AI-Fitness/fitbuddy-argocd.git
    targetRevision: main

  - name: fitbuddy-prod
    namespace: production
    valueFile: values-prod.yaml
    repoURL: https://github.com/FitBuddy-AI-Fitness/fitbuddy-argocd.git
    targetRevision: main
