apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitbuddy-workout-service
  labels:
    app: fitbuddy-workout-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fitbuddy-workout-service
  template:
    metadata:
      labels:
        app: fitbuddy-workout-service
        {{- if .Values.workloadIdentity.enabled }}
        azure.workload.identity/use: "true"
        {{- end }}
    spec:
      serviceAccountName: fitbuddy-sa-workout-service
      containers:
        - name: workout-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          envFrom:
            - configMapRef:
                name: fitbuddy-config-workout-service
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5

