environment: production
image:
  repository: acrfitbuddyprod.azurecr.io/user-service
  tag: v1.1.0
service:
  port: 5002
replicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
resources:
  requests:
    cpu: "25m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"
workloadIdentity:
  enabled: true
  clientId: "7c1a4ce0-4562-4ae6-94ec-1b1c0b72981d"
  tenantId: "bcbf2065-8fdc-47ff-9ee6-a739631314aa"
keyVaultName: "kv-fitbuddy-8iuym63"
