environment: dev
image:
  repository: acrfitbuddyprod.azurecr.io/user-service
  tag: 0a5a00ef287ea0e7eb9ddca43cd151f3abd90aa9
service:
  port: 5002
replicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
resources:
  requests:
    cpu: "25m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

workloadIdentity:
  enabled: true
  clientId: "YOUR-AZURE-MANAGED-IDENTITY-CLIENT-ID"
