apiVersion: v1
kind: Service
metadata:
  name: diet-service
  labels:
    app: fitbuddy-diet-service
spec:
  type: ClusterIP
  selector:
    app: fitbuddy-diet-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
