apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workout-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/FitBuddy-AI-Fitness/fitbuddy-argocd.git
    targetRevision: main
    path: charts/workout-service
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
