environment: dev

image:
  repository: aravindacr.azurecr.io/fitbuddy-progress-service
  tag: latest

service:
  port: 3004

ingress:
  enabled: true
  className: kgateway
  host: dev.fitbuddy.local
  path: /progress

workloadIdentity:
  enabled: true
  clientId: "YOUR-AZURE-MANAGED-IDENTITY-CLIENT-ID"

replicaCount: 2

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
