environment: dev
image:
  repository: acrfitbuddyprod.azurecr.io/chatbot-service
  tag: "7937e42"
service:
  port: 5005
replicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
workloadIdentity:
  enabled: true
  clientId: "YOUR-AZURE-MANAGED-IDENTITY-CLIENT-ID"
  tenantId: "YOUR-AZURE-TENANT-ID-HERE"

keyVaultName: "YOUR-KEY-VAULT-NAME-HERE"
