environment: production
image:
  repository: aravindacr.azurecr.io/fitbuddy-chatbot-service
  tag: v1.0.0
service:
  port: 3002
replicaCount: 3
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

workloadIdentity:
  enabled: true
  clientId: "YOUR-AZURE-MANAGED-IDENTITY-CLIENT-ID"
