environment: production
image:
  repository: acrfitbuddyprod.azurecr.io/auth-service
  tag: v5.9-beta.1
service:
  port: 5001
replicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
resources:
  requests:
    cpu: "25m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"
workloadIdentity:
  enabled: true
  clientId: "9690ce92-05ca-4001-8d50-5c24ad8b749c"
  tenantId: "bcbf2065-8fdc-47ff-9ee6-a739631314aa"
keyVaultName: "kv-fitbuddy-8iuym63"
